### PR TITLE
Update pfp

### PR DESCRIPTION
**Pull request by Aresiel**

### CODE REVIEW

**Comment by Sid200** [comment]
Bad

**Comment by Aresiel** [comment]
wrong, lgtm

**Comment by Sid200** [comment]
Use svg

**Comment by Aresiel** [comment]
lgtm = let's get this merged

**Comment by Aresiel** [comment]
merge!

**Comment by Sid200** [comment]
CRY

**Comment by Aresiel** [comment]
nope, merge

**Comment by Aresiel** [comment]
MERGE!

**Comment by Sid200** [comment]
# NEVER

**Comment by Aresiel** [comment]
NOW
===

**Comment by Sid200** [comment]
😭

**Comment by Aresiel** [comment]
lgtm

**Comment by Sid200** [comment]
L**n**gtm

**Comment by Aresiel** [comment]
looks not garbage to me? great, so merge it

**Pull request closed without merging**
